### ISSUE TITLE
From time to time: PHP Fatal error:  Uncaught ValueError: fread(): Argument #2 ($length) must be greater than 0

### ISSUE THREAD

**Issue by iammeken** [ericsizemore/simple_counter#3]
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ValueError: fread(): Argument #2 ($length) must be greater than 0 in xxx/counter/counter.php:209
Stack trace:
#0 xxx/counter/counter.php(209): fread()
#1 xxx/counter/counter.php(234): Esi\SimpleCounter\Counter->readWriteFile()
#2 xxx/counter/counter.php(273): Esi\SimpleCounter\Counter->process()
#3 xxx/index.php(401): include('...')
#4 {main}
  thrown in xxx/counter/counter.php on line 209" while reading upstream,

**Comment by ericsizemore** [comment]
Thank you for the report @iammeken :) I've never personally encountered this issue, however, could you try something for me? I believe this will resolve it for you.

In counter.php find:

`if (self::USE_FLOCK AND \flock($fp, \LOCK_EX)) {`

And before that, add:

`\clearstatcache();`

Should look something like this:

```
\clearstatcache();

if (self::USE_FLOCK AND \flock($fp, \LOCK_EX)) {
```

**Comment by iammeken** [comment]
I guess it was caused by **naughty** visitors/bots.

```
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string + int in xxx/counter/counter.php:252
Stack trace:
#0  xxx/counter/counter.php(274): Esi\SimpleCounter\Counter->process()
#1  xxx/index.php(401): include('...')
#2 {main}
  thrown in xxx/counter/counter.php on line 252" while reading upstream, client: 90.156.169.15, server: default, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "xxx.com"
2023/06/25 05:28:02 [error] 2168#2168: *327204 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ValueError: fread(): Argument #2 ($length) must be greater than 0 in xxx/counter/counter.php:210
Stack trace:
#0  xxx/counter/counter.php(210): fread()
#1  xxx/counter/counter.php(235): Esi\SimpleCounter\Counter->readWriteFile()
#2  xxx/counter/counter.php(274): Esi\SimpleCounter\Counter->process()
#3  xxx/index.php(401): include('...')
#4 {main}
```

**Comment by iammeken** [comment]
I checked one such ip address:

They visited the script via several different domains at the same second.
